version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "20:00"
    open-pull-requests-limit: 10
    reviewers:
      - "mashiike"
    ignore:
      - dependency-name: "github.com/aws*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"
