version: "2"

linters:
  settings:
    gocyclo:
      min-complexity: 40
    errcheck:
      exclude-functions:
        - "fmt.Print*"
        - "fmt.Fprint*"
        - "fmt.Fprintln"
        - "io.WriteString"
        - "(io.ReadCloser).Close"
        - "(flag.Value).Set"
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
  default: none
  enable:
    - govet
    - errcheck
    - gocyclo
    - ineffassign
    - unused
    - staticcheck
    - unconvert
    - goconst

formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mashiike

  enable:
    - gofmt
    - goimports

run:
  timeout: 5m

