name: Test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.25.1"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Build & Test
        run: |
          go test -race ./...
        env:
          TZ: "Asia/Tokyo"
